###

POST localhost:8071/createacc/1

###

POST localhost:8071/createacc/2

###
###

POST localhost:8071/update/1/1234

###

POST localhost:8071/update/2/284

###

POST localhost:8071/transfer
Content-Type: application/json

{
  "sourceId": 1,
  "destinationId": 2,
  "value": 1000
}
###
